name:                adventofcode
version:             0.1.0.0
github:              "githubuser/adventofcode"
license:             BSD3
author:              "Kris Jenkins"
maintainer:          "krisajenkins@gmail.com"
copyright:           "2018-2021 Kris Jenkins"

data-files:
- data/*/Day*.txt
extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/adventofcode#readme>

dependencies:
- base >= 4.7 && < 5
- array
- bytestring
- comonad
- containers
- extra
- foldl
- free
- lens
- logict
- megaparsec
- mtl
- newtype-generics
- recursion-schemes
- safe
- split
- tardis
- text
- time
- transformers
- vector

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wnoncanonical-monad-instances
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wredundant-constraints
    - -Widentities

tests:
  adventofcode:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
    - hspec
    - QuickCheck
